%JARED OTIENO FWAYA
%S13/09256/17
%ASSIGNMENT

aunt(ann,job).
female(ann).
father(james,job).
brother(james,ann).
mother(mary,job).
uncle(mike,job).
brother(james,mike).
male(mike).
different(mike,job).
cousin(ian,job).
father(mike,ian).
step-father(james,milly).
husband(james,winnie).
mother(winnie,milly).
biological_father(andrew,milly).
different(james,andrew).
male(andrew).
step-mother(winnie,job).
half-brother(job,millly).
male(job).
half-sister(milly,job).
female(milly).
grand-father(cliff,job).
father(cliff,james).
male(cliff).
great-grandfather(philip,job).
father(philip,cliff).
grand-father(cliff,job).
male(philip).
aunt(ann,job):-female(ann),father(james,job),sister(ann,james).
uncle(mike,job):-brother(james,mike),male(mike),different(mike,job),father(cliff,james),father(cliff,mike).
cousin(ian,job):-father(mike,ian),brother(james,mike),father(james,job).
step-father(james,milly):-husband(james,winnie),mother(winnie,milly),biological_father(andrew,milly),different(james,andrew),male(andrew),male(james).
half-brother(job,millly):-male(job).
half-sister(milly,job):-female(milly).
grand-father(cliff,job):-father(cliff,james),father(james,job),male(cliff).
great-grandfather(philip,job):-father(philip,cliff),grand-father(cliff,job),male(philip).

